### ISSUE TITLE
Mute Icon

### ISSUE THREAD

**Issue by hroch** [muchino/confluence.chat#102]
Could you please switch position of chat icon and mute icon on expanded panel?
Motivation: When user want to open chat, he need to point a cursor on icon and then click. Mute button immediately appears bellow the cursor, so user will probably mute the chat by accident.

Maybe you could move mute button into top navigation panel, next to the options.
![1](https://cloud.githubusercontent.com/assets/7569389/4732289/b9b681d8-59b9-11e4-8303-8b826d3d9037.JPG)
![2](https://cloud.githubusercontent.com/assets/7569389/4732288/b9b653ac-59b9-11e4-84d9-501e274ee568.JPG)
![3](https://cloud.githubusercontent.com/assets/7569389/4732287/b9b55f7e-59b9-11e4-8cda-634dded0d0e6.JPG)

**Comment by muchino** [comment]
An update will available soon
