### ISSUE TITLE
idle chat preventing user session timeout?

### ISSUE THREAD

**Issue by mariade** [muchino/confluence.chat#105]
Hello muchino et. al, 

I am wondering if Confluence Chat could be preventing users from having a session timeout after the default 60 minutes. ( https://confluence.atlassian.com/display/CONFKB/How+to+Adjust+the+Session+Timeout+for+Confluence )
Our users who are inactive for well beyond the 60 minute mark are not logged out and the only reason I can think of why is that there have been changes in the Chat even though the user has not actively participated. 

Thoughts on this? Solutions or suggestions? All is appreciated.

**Comment by muchino** [comment]
Hi

The chat requested is "logged in" with the current user. And this request
prevents (by system architecture of confluence) that the user automatically
logged of.

I can't don anything against this.

2015-02-02 11:58 GMT+01:00 mariade <notifications@github.com>:

**Comment by mariade** [comment]
I understand, thank you!
