### ISSUE TITLE
Hide in editor not working

### ISSUE THREAD

**Issue by gmask** [muchino/confluence.chat#107]
Version: 2.0.4

When I check the "Yes" box in chat configuration for "Hide in editor" the chat window still appears on the edit screens in all spaces, obscuring the "Cancel" button.

**Comment by muchino** [comment]
Which confluence version you are using?

gmask <notifications@github.com> schrieb am Fr., 13.02.2015, 20:26:

**Comment by gmask** [comment]
We are running Confluence 5.6.6, though this was also occurring in a previous version (I believe it was 5.6.2)

**Comment by muchino** [comment]
I realy sorry, but I can't reproduce your issue - it's working for me in 5.6.2 and 5.6.6
