### ISSUE TITLE
Chat not working after 2.0.5 update

### ISSUE THREAD

**Issue by mariade** [muchino/confluence.chat#109]
Our Confluence chat has stopped working after upgrading to 2.0.5. After sending a message it does not show up in the chat and the user does not receive it. No error is given.

We are using Confluence version 5.6.3. What can we do to fix this? 

We miss our chat :( Thanks!

**Comment by muchino** [comment]
you activated and deactivated the add-on already?

**Comment by muchino** [comment]
Could you send me the atlassian-confluence.log file?  Located in the home
directory of confluence.
I hope that i can find the reason.

Are the histories empty too?

mariade <notifications@github.com> schrieb am Mi., 25.02.2015, 15:58:

**Comment by muchino** [comment]
Could you send me the atlassian-confluence.log file?  Located in the home
directory of confluence.
I hope that i can find the solution ther

mariade <notifications@github.com> schrieb am Mi., 25.02.2015, 15:58:

**Comment by muchino** [comment]
I found the issue, an update will available soon

**Comment by mariade** [comment]
It's working great again! Vielen Dank!
