### ISSUE TITLE
Confluence Chat appears to cause 'Aw, Snap' errors in the latest version of Chrome

### ISSUE THREAD

**Issue by ldally** [muchino/confluence.chat#111]
We (Atlassian Support) have had a handful of reports from customers that they're seeing Chrome crash when multiple tabs are open. All have have Confluence Chat installed, and disabling the plugin has prevented the crashes. If you're after any more information, I can either ask the customers on your behalf or refer them onto you, whichever you'd prefer :)

**Comment by muchino** [comment]
Sorry for my so delayed respone, no idea why I forgot it or never seen this ticket before. 
Sounds like a bug - which will be hard to find the reason for. 

Of course - any information can help :) like:
- how many tabs
- confluence version
- how many users are online at the same time

thank you and sorry again :(

**Comment by ldally** [comment]
Hi Oliver,

This KB article contains everything we know about the problem:
https://confluence.atlassian.com/display/CONFKB/Aw+Snap+errors+in+Google+Chrome

I'm not sure if we ever thought to ask how many users were online
simultaneously, but we can definitely collect that information in the
future. I've added a section to that KB article asking for the details
you're after.

Cheers,
Lachlan
