### ISSUE TITLE
Chat hides the Close button in Editor help

### ISSUE THREAD

**Issue by mmjau** [muchino/confluence.chat#112]
I have already chosen "Hide in Editor" but it doesnt do anything. Looks like this:
![hiding the close button](https://cloud.githubusercontent.com/assets/12950631/8229228/47110b7c-15b5-11e5-89dc-55c7771bed5a.png)

Version: Confluence 5.7

**Comment by muchino** [comment]
Sorry for this issue

I will have a look into this. Are you using the Confluence built in theme or the documentation theme?

**Comment by muchino** [comment]
I changed this in the next version, which will be released in the next few days.
