### ISSUE TITLE
confluence.chat causes high cpu load

### ISSUE THREAD

**Issue by MattPaGis** [muchino/confluence.chat#113]
Hi,

after installing confluence.chat we noticed, that cpu load increases over time (a couple of hours) up to 100 %. Clearing the cache drops the cpu load until it increases again. Also actions within the UPM like disabling, installing plugins drops the load to a normal level.
The system specs:
    Windows 2012 Server (64 bit)
    Intel Xeon CPU E5-4620 2.2 Ghz - 2.93 Ghz (2 Processors)
    8 GiB RAM
    Virtuel machine

Other applications:
    Jira 6.4.1
    The high CPU Usage is caused by the Tomcat confluence process!

Please let me know wether you need further information.
Thanks in advance
Matt

**Comment by muchino** [comment]
Hi matt

How many concurrent  users are active?
Which Browser version you are using?

Oli
Am 11.08.2015 14:34 schrieb "MattPaGis" <notifications@github.com>:

**Comment by MattPaGis** [comment]
Hi Oli,

about 100 Users are logged in. Most of them with IE9.

regards Matt

**Comment by muchino** [comment]
The only thing you can ply with is the heartbeat in the configurations - increase it to more than a second
