### ISSUE TITLE
Usernames in confluence chat does not synchronize with AD after change

### ISSUE THREAD

**Issue by josherfs** [muchino/confluence.chat#115]
Dear Support,

We notice that the username that is visible in confluence chat does not synchronize with the username in the AD after the username in the AD has been changed. The new name will be visible in confluence but not in the confluence chat which still uses the old name
We use confluence 5.7.5. and Confluence chat version 2.0.6.
Can you help us solve this issue?

Jos Herfs

**Comment by muchino** [comment]
Have you tried deactivate the plugin and activate it again.  Sounds like a
caching issue
Am 17.11.2015 15:23 schrieb "josherfs" <notifications@github.com>:

**Comment by josherfs** [comment]
Hi Oliver,

We tried in our test environment and this seems to work, we go try it in Production later today to minimize the impact on the users.

Jos Herfs
Intranet Service

Van: Oliver Straesser [mailto:notifications@github.com]
Verzonden: dinsdag 17 november 2015 17:58
Aan: muchino/confluence.chat
CC: Intranet Services
Onderwerp: Re: [confluence.chat] Usernames in confluence chat does not synchronize with AD after change (#115)

Have you tried deactivate the plugin and activate it again. Sounds like a
caching issue
Am 17.11.2015 15:23 schrieb "josherfs" <notifications@github.com<mailto:notifications@github.com>>:

> Dear Support,
>
> We notice that the username that is visible in confluence chat does not
> synchronize with the username in the AD after the username in the AD has
> been changed. The new name will be visible in confluence but not in the
> confluence chat which still uses the old name
> We use confluence 5.7.5. and Confluence chat version 2.0.6.
> Can you help us solve this issue?
>
> Jos Herfs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muchino/confluence.chat/issues/115>.
>


—
Reply to this email directly or view it on GitHub<https://github.com/muchino/confluence.chat/issues/115#issuecomment-157431428>.

------------------------------------------------------------------------------------------------------
ATTENTION:
The information in this e-mail is confidential and only meant for the intended recipient. If you are not the intended recipient , don't use or disclose it in anyway. Please let the sender know and delete the message immediately.
------------------------------------------------------------------------------------------------------
