### ISSUE TITLE
Delete History when user is not available

### ISSUE THREAD

**Issue by umdkevin** [muchino/confluence.chat#116]
so I see how to delete the history when the other user is online through the chat window. But can there be a delete chat history from another window/option when the user is not available/online?

**Comment by muchino** [comment]
from within your chat history in you profile area could be a solution

**Comment by umdkevin** [comment]
right, that's what I would think as well. Are you still making updates? A button/option to delete the history from the user profile would be a good addition.

**Comment by muchino** [comment]
I changed it as requested - because it's making sense :) I will deploy it next week I think. If I doesn't - just push me to do it ;) :D
