### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by parsonsk** [muchino/confluence.chat#117]
I am seeing java.lang.NumberFormatException in the log at confluence.chat.actions.AbstractChatAction.start(AbstractChatAction.java:70). From the source I see: 
`if (StringUtils.isNumeric(parameterPageId)) {
     Long pageId = new Long(parameterPageId);`
I think that (for some reason - maybe another plugin) that pageId is "" on the page in question. StringUtils.isNumeric("") returns true, but I think that parseLong will throw an exception for "".

**Comment by muchino** [comment]
I'm currently working on a new version, so I'll try to catch it.

Oli
Am 12.02.2016 17:03 schrieb "parsonsk" <notifications@github.com>:

**Comment by muchino** [comment]
I could reproduce the error and solved it already local. so will be solved with the next version (around next week)
