### ISSUE TITLE
Remove Chat History

### ISSUE THREAD

**Issue by astronut13** [muchino/confluence.chat#118]
I've tried disabling both chat history tabs and the confluence chat histories modules. However, it doesn't completely remove the option of navigating to the chat history (the option still appears in chat windows and the general chat list) and also makes the whole chat add-on very buggy (i.e. it displays a blank user list).

**Comment by muchino** [comment]
If you disable some modules - yes of course it cut be buggy ;) 

maybe you have some steps to reproduce your issues? 
Thank you
oli

**Comment by astronut13** [comment]
The FAQ recommends disabling those modules to remove the history; I was
just following the directions.

On Wed, Feb 17, 2016 at 11:03 AM, Oliver Straesser <notifications@github.com
> wrote:

> If you disable some modules - yes of course it cut be buggy ;)
>
> maybe you have some steps to reproduce your issues?
> Thank you
> oli
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muchino/confluence.chat/issues/118#issuecomment-185272576>
> .
>



-- 
***************************
Jonathan Kyle, Ph.D.
Columbia University
Cell Phone: (585) 732-9343
***************************

**Comment by muchino** [comment]
Ok I will have a look to this and will update the FAQ if needed within this week - maybe it's the best if I add an configuration to hide the history, so it become more easy for all :)

**Comment by muchino** [comment]
I implemented the functionality today - but I need some more time for testing ;)
