### ISSUE TITLE
Offline contacts and send message via email if a user is offline

### ISSUE THREAD

**Issue by loverde** [muchino/confluence.chat#26]
When in the middle of a chat, if the user logs off, it would be nice if there was an option to send them an email containing the contents of the message that was sent.  If you could send directly to offline contacts, this might also be a nice way to "invite" someone to a chat conversation.  Then the recipient could choose to either response via email, or to click a link in the email to log into Confluence and join the chat.

**Comment by muchino** [comment]
because I don't like to spam the user I won't do that
