### ISSUE TITLE
Window obscuring buttons on edit screen

### ISSUE THREAD

**Issue by shanefisher** [muchino/confluence.chat#87]
If the chat window is open then it obscures the save etc buttons on the bottom right of Confluence edit screen. This means you either have to use keyboard short-cuts or close the chat window to click the buttons. Perhaps it should either close itself (just the list of users) on the edit screen or move to the left hand side of the screen to avoid obscuring the buttons.
Not unusable in its current form but we have had feedback from new users that they couldn't find the buttons because the chat window had hidden them.

**Comment by muchino** [comment]
I changed this in the next version, which will be released in the next few days.
