### ISSUE TITLE
Chat sound and browser tab updates when user not logged in

### ISSUE THREAD

**Issue by pcondon2** [muchino/confluence.chat#97]
![chatissue](https://cloud.githubusercontent.com/assets/4673512/4210186/b184cf82-3872-11e4-8241-d707a8775ce2.JPG)

Periodically, I will get audio sound for chat and the browser tab title will change but the user is not logged in.

In the example from attachment, I did have chat session with this user yesterday but not today.

The only thing I know to do is close browser session.  Typically I use latest version of Firefox and Confluence Chat 2.0.4

Thanks

**Comment by muchino** [comment]
sorry I can't reproduce this issue
