### ISSUE TITLE
Chat function disappearing 

### ISSUE THREAD

**Issue by candelle** [muchino/confluence.chat#98]
Hi, 
I am managing a number of spaces on the DropIN confluence site and all of our users across all spaces are experiencing irregularities with the chat function.  At times it appears in the bottom right hand corner, however most of the time it is not visible.  Is this a bug or is it an issue with our settings?  How could we go about resolving this?

Cheers, 

Candelle

**Comment by muchino** [comment]
I catch it now (I know after more as a year - but it was a though one ;) )
